swagger: "2.0"
info:
  title: Dekh Tamasha - A Movie Rating API
  description: Watch movies that are worth your time
  version: 0.0.1
host: 192.168.227.243:5000
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

definitions:
  Movie:
    properties:
      99popularity:
        type: number
        example: 78.0
      director:
        type: string
        example: Bret Ratner
      genre:
        type: array
        items:
          example: "Comedy"
      imdbScore:
        type: number
        example: 7.0
      name:
        type: string
        example: Rush Hour
    required:
      - 99popularity
      - director
      - imdbScore
      - name

  User:
    properties:
      userId:
        type: integer
        example: 001
      firstName:
        type: string
        example: Jackie
      userName:
        type: string
        example: chanjackie
      email:
        type: string
        example: chanjackie@fynd.com
      accessRole:
        type: string
        example: User
    required:
      - fullName
      - loginName
      - email
      - accessRole

paths:
  /movies:
    get:
      operationId: resources.movie_resource.get_all
      tags:
        - View Movies
      summary: Detailed list of all Movies
      description: View all the movies
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Internal Server Error.
        504:
          description: Gateway Timeout.
          schema:
            $ref: "#/definitions/Movie"
  /users:
    get:
      operationId: resources.user_resource.get_all
      tags:
        - View Users
      summary: Detailed list of all Users
      description: View all the users
      produces:
        - application/json
      responses:
        200:
          description: OK
        500:
          description: Internal Server Error.
        504:
          description: Gateway Timeout.
          schema:
            $ref: "#/definitions/User"
  /movie:
    post:
      operationId: resources.movie_resource.add_movie
      tags:
        - Add Movie
      summary: Add A Movie
      description: Adding movie details
      parameters:
        - name: movie_json
          in: body
          required: True
          schema:
            $ref: "#/definitions/Movie"
      responses:
        201:
          description: CREATED
          schema:
            $ref: "#/definitions/Movie"
